Fixes for Multi-sample, implementation of MuData and Docs for hashing
theislab/hadge pull request #20
Opened 2023-08-25 13:02 UTC by mari-ga

* Multiple fixes for multi-sample hashing
* implementation of MuData for summary hashing demultiplexing
* Added docs for new tools hashing (GMM-Demux, BFF and Demuxmix)
* Other fixes (correction of parameter for BFF)

2023-08-25 20:22 UTC, wxicu requested changes

2023-08-28 13:36 UTC, mari-ga commented on modules/hash_demulti/preprocess.nf
> +        val normalisation_methodx
Yes, deleted x on next update

2023-08-28 13:36 UTC, mari-ga commented on modules/hash_demulti/preprocess.nf
> +        preprocess(input_list, hto_raw_or_filtered, rna_raw_or_filtered,sel_method, ndelim, n_features, assay, margin, norm_method, out_file, gene_col)
simply checking the order or arguments, back in original order

2023-10-25 19:29 UTC, wxicu commented
Hey @mari-ga sorry I didnt see this earlier, is this ready for review now?

2023-10-31 08:55 UTC, Zethson commented
@mari-ga what's the status of this PR?

2023-11-06 15:18 UTC, wxicu commented on bin/summary_hash.py
> +        if raw_mudata is not None:
also add HTO please

2023-11-06 15:19 UTC, wxicu commented on bin/summary_hash.py
> +            mudata.write("hash_summary/mudata/mudata_with_mudata_"+ os.path.basename(x)+".h5mu")
`mudata_with` instead of `mudata_with_mudata_`

2023-11-06 15:27 UTC, wxicu commented on nextflow.config
> +
please remove empty lines

2023-11-06 15:39 UTC, wxicu requested changes
Thanks @mari-ga for the contribution! The code looks good, just need some minor changes

2023-11-06 15:39 UTC, wxicu commented on nextflow.config
> +             executor = 'local'
executor should be slurm

2023-11-06 15:39 UTC, wxicu commented on modules/hash_demultiplexing.nf
> +        print("BFF path to output")
why print this out?

2023-11-06 17:50 UTC, merged